apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
type: Opaque
data:
  # These are placeholder values that should be replaced with actual secrets
  # The values should be base64 encoded
  REDIS_PASSWORD: UmVkaXNQYXNzd29yZDEyMzQ1Ng==
