apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
type: Opaque
data:
  # These are placeholder values that should be replaced with actual secrets
  # The values should be base64 encoded
  JWT_SECRET: UHJvZHVjdGlvbkpzb25XZWJUb2tlblNlY3JldEtleQ==
