apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: migratio-production

bases:
- ../base/api-gateway
- ../base/user-service
- ../base/assessment
- ../base/recommendation
- ../base/program-service
- ../base/roadmap-service
- ../base/pdf-service
- ../base/client
- ../base/mongodb
- ../base/redis

resources:
- namespace.yaml
- ingress.yaml
- service-endpoints.yaml

patchesStrategicMerge:
- api-gateway-config.yaml
- api-gateway-secrets.yaml
- redis-config.yaml
- redis-secrets.yaml
- mongodb-config.yaml
- mongodb-secrets.yaml

commonLabels:
  environment: production
