apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  MONGODB_HOST: "mongodb.migratio-production.svc.cluster.local"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "migratio_production"
