apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- secrets.yaml
- hpa.yaml
- networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: api-gateway
  app.kubernetes.io/part-of: migratio
  app.kubernetes.io/component: backend
