services:
  # Program Service API
  - type: web
    name: migratio-program-service
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PROGRAM_SERVICE_PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This will be set manually in the Render dashboard
    healthCheckPath: /
    autoDeploy: true
